pipeline:
  firefox:
    image: selenium/node-firefox
    detach: true
    environment:
      - HUB_PORT_4444_TCP_ADDR=selenium-hub
      - HUB_PORT_4444_TCP_PORT=4444
  chrome:
    image: selenium/node-chrome
    detach: true
    environment:
      - HUB_PORT_4444_TCP_ADDR=selenium-hub
      - HUB_PORT_4444_TCP_PORT=4444
  test:
    image: maven:alpine
    commands:
     - mvn clean test
     - mvn clean install
    when:
      events:
        - push
        - pull_request
  report:
    junit:
       - /Users/mmuvva/Selenium/junit.xml
services:
  selenium-hub:
    image: selenium/hub