pipeline: 
  build: 
    commands: "mvn package -DskipTests=true"
    image: "sample/test-maven:latest"
  test: 
    commands: "mvn clean test"
    image: "sample/test-maven:latest"
    when: 
      events: 
        - push
        - pull_request
services:
  selenium:
    image: selenium/hub

  chrome:
    image: selenium/node-chrome
    environment:
      SE_OPTS: "-port 4445"
      HUB_PORT_4444_TCP_ADDR: 127.0.0.1
      HUB_PORT_4444_TCP_PORT: 4444

  firefox:
    image: selenium/node-firefox
    environment:
      SE_OPTS: "-port 4446"
      HUB_PORT_4444_TCP_ADDR: 127.0.0.1
      HUB_PORT_4444_TCP_PORT: 4444
      DISPLAY: ":98.0"