pipeline:
  test:
    image: node:latest
    commands:
      - yarn install
      - yarn build
      - yarn start
      - yarn test

services:
selenium-hub:
  image: selenium/hub
  ports:
    - "4444:4444"

chrome:
    image: selenium/node-chrome-debug
    ports:
    - 5902:5900
    links:
      - selenium-hub:hub
    volumes:
      - /dev/shm:/dev/shm # Mitigates the Chromium issue described at https://code.google.com/p/chromium/issues/detail?id=519952

firefox:
    image: selenium/node-firefox-debug
    ports:
    - 5901:5900
    links:
      - selenium-hub:hub