pipeline: 
  test: 
    commands: "mvn clean install -DBROWSER=dockerchrome"
    image: "sample/test-maven:latest"
    when: 
      events: 
        - push
        - pull_request
services:
  selenium-hub:
    image: selenium/hub    
  chrome:
    image: selenium/node-chrome-debug
    volumes:
      - /dev/shm:/dev/shm # Mitigates the Chromium issue described at https://code.google.com/p/chromium/issues/detail?id=519952
  firefox:
    image: selenium/node-firefox-debug
   