pipeline: 
  test: 
    commands: "mvn clean install -DBROWSER=dockerchrome"
    image: "sample/test-maven:latest"
    when: 
      events: 
        - push
        - pull_request
services:
  selenium-hub:
    image: selenium/hub
  chrome:
    image: selenium/node-chrome
    environment:
      SE_OPTS: "-port 4445"
      HUB_PORT_4444_TCP_ADDR: selenium-hub
      HUB_PORT_4444_TCP_PORT: 4444

  firefox:
    image: selenium/node-firefox
    environment:
      SE_OPTS: "-port 4446"
      HUB_PORT_4444_TCP_ADDR: selenium-hub
      HUB_PORT_4444_TCP_PORT: 4444
      DISPLAY: ":98.0"